name: Auto Merge

run-name: Auto Merge

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        uses: liblaf/actions/auto-merge@main
        with:
          token: ${{ secrets.PAT || github.token }}
