name: Auto Review

on:
  pull_request:
  workflow_dispatch:

jobs:
  review:
    name: Review
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Review
        uses: liblaf/actions/auto-review@main
        with:
          token: ${{ secrets.PAT || github.token }}
