name: Auto Label Sync

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  label-sync:
    name: Label Sync
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Label Sync
        uses: EndBug/label-sync@v2
        with:
          config-file: https://github.com/liblaf/.github/raw/refs/heads/main/.github/labels.yaml
          delete-other-labels: false
