name: Auto Copier Update

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  copier-update:
    name: Copier Update
    permissions:
      actions: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || github.token }}
      - name: Copier Update
        uses: liblaf/actions/copier-update@main
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(copier): update from template"
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
          commit_author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
