name: CI

on:
  push:
  release:
    types:
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Pack
        run: pnpm pack
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pack
          path: "*.tgz"

  publish:
    name: Publish
    permissions:
      id-token: write
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies
        run: pnpm install
      - name: Publish
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  pre-release:
    name: Pre-Release
    permissions:
      contents: write
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: pack
          path: pack/
      - name: Create Pre-Release
        uses: liblaf/actions/release@main
        with:
          clobber: true
          files: pack/*
          prerelease: true
          tag: latest

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: pack
          path: pack/
      - name: Create Pre-Release
        uses: liblaf/actions/release@main
        with:
          files: pack/*
          tag: ${{ github.event.release.tag_name }}
